#:schema https://api.nuon.co/v1/general/config-schema?source=docker_build

name       = "docker_image"
type       = "docker_build"
dockerfile = "Dockerfile"

[public_repo]
repo      = "nuonco/guides"
directory = "aws-ecs-tutorial/components/docker-image"
branch    = "main"
