#:schema https://api.nuon.co/v1/general/config-schema?source=terraform_module
name              = "certificate"
type              = "terraform_module"
terraform_version = "1.5.3"

[public_repo]
repo      = "nuonco/guides"
directory = "aws-eks-tutorial/components/certificate"
branch    = "main"

[vars]
domain_name = "introspect.{{.nuon.install.sandbox.outputs.public_domain.name}}"
zone_id     = "{{.nuon.install.sandbox.outputs.public_domain.zone_id}}"
