#:schema https://api.nuon.co/v1/general/config-schema

# This file contains values for common Nuon application configuration options.
# To use it for your app, edit as needed, create an application called aws-ecs-app and run
#
#   nuon apps sync -c nuon.aws-ecs-app.toml
#
# See https://docs.nuon.co/concepts/apps for more information.

version = "v1"
description = "AWS ECS Demo Application."
display_name = "Nuon AWS ECS Demo App"
slack_webhook_url = "https://slack.nuon.co"

[installer]
source = "installer.toml"

[runner]
source = "runner.toml"

[sandbox]
source = "sandbox.toml"

[inputs]
source = "inputs.toml"

[[components]]
source = "components/docker_image.toml"

[[components]]
source = "components/ecs_service.toml"
